modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="quest_giver"
version="${file.jarVersion}"
displayName="Quest Giver"
logoFile="quest_giver.png"
credits="Feywild Community"
authors="Saphie"
description='''
Quest Giver.
'''

[[dependencies.quest_giver]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quest_giver]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quest_giver]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.1-3.2.17,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quest_giver]]
    modId="morevillagers"
    mandatory=true
    versionRange="[1.18.2-3.2.0,)"
    ordering="BEFORE"
    ide="BOTH"

[[dependencies.quest_giver]]
    modId="guardvillagers"
    mandatory=true
    versionRange="[1.4.1,)"
    ordering="BEFORE"
    ide="BOTH"

[[dependencies.quest_giver]]
    modId="bk"
    mandatory=true
    versionRange="[1.0.0.4,)"
    ordering="BEFORE"
    ide="BOTH"

[[dependencies.quest_giver]]
    modId="afptweaks"
    mandatory=true
    versionRange="[1.1.0,)"
    ordering="BEFORE"
    ide="BOTH"

[[dependencies.quest_giver]]
    modId="reputation"
    mandatory=true
    versionRange="[0.4.0,)"
    ordering="BEFORE"
    ide="BOTH"